### ISSUE TITLE
Establish server/database

### ISSUE THREAD

**Issue by brendanphilbin** [csci312-s21/project-amber-ayeaye#19]
Get a database up and running for us to store our data. Songs and playlists should be stored in the database.

**Comment by mylesstokowski** [comment]
I think we might be good to close this issue?

**Comment by Ntare62** [comment]
should we wait until we have the API routes

**Comment by mylesstokowski** [comment]
What about closing this and making a more specific issue for writing the API routes? I'm fine either way though

**Comment by Ntare62** [comment]
That sounds good to me.
