### ISSUE TITLE
Auto-refresh current playlist on listener view

### ISSUE THREAD

**Issue by majacannavo** [csci312-s21/project-amber-ayeaye#32]
As a listener, I want the main listener page to auto-refresh every [x seconds] so that I can always see the most up-to-date playlist information without having to manually refresh the page.

**Comment by brendanphilbin** [comment]
Potential alternative: periodically re-render to the current playlist component to avoid a full refresh of the whole site

**Comment by mylesstokowski** [comment]
Potentially use WebSocket/talk with Professor Andrews
