### ISSUE TITLE
Listener page design

### ISSUE THREAD

**Issue by brendanphilbin** [csci312-s21/project-amber-ayeaye#35]
As a listener I want the home page of the website to play the radio [SEE LISTENER BUTTON], present the radio station's schedule, the most recent (or current, if applicable) playlist, and a way to explore past playlists [SEE PLAYLIST EXPLORER] so that I can have a complete picture of the radio station on one page.

**Comment by mylesstokowski** [comment]
Hierarchical: relies on completing playlist explorer, schedule, play button, and log in
