### ISSUE TITLE
As a DJ, I would like a way to edit my show's description after logging in, so that my listeners can see details about my show while listening.

### ISSUE THREAD

**Issue by mylesstokowski** [csci312-s21/project-amber-ayeaye#43]
Class Name: ShowBioEditor

Responsibilities: is able to differentiate between DJ's so that a DJ can only edit their own description. Create a endpoint that can handle posting new descriptions into the DB

Collaborators: Authentication, show data structure, SQLite DB

**Comment by majacannavo** [comment]
Did not have time for
